namespace FTree.Common
{
    /// <summary>
    /// Contains names of all string stored in resource file of this assembly.
    /// </summary>
    public enum StringResName
    {
        ERR_DELETE_ENTRY_FAILED,
        ERR_DELETE_FAMILY_FAILED,
        ERR_DELETE_PERSON_FAILED,
        ERR_DELETE_RELATION_TYPE_FAILED,
        ERR_ENTRY_ALREADY_EXIST,
        ERR_FAMILY_ALREADY_EXIST,
        ERR_FIND_RELATIONSHIP_FAILED,
        ERR_INSERT_PERSON_FAILED,
        ERR_INSERT_FAMILY_FAILED,
        ERR_INSERT_NEW_ENTRY_FAILED,
        ERR_INSERT_RELATION_TYPE_FAILED,
        ERR_INVALID_BIRTHDAY,
        ERR_INVALID_DATE,
        ERR_LOAD_DATA_FAILED,
        ERR_LOADING_DATA,
        ERR_LOAD_FAMILIES_FAILED,
        ERR_LOAD_FTREE_FAILED,
        ERR_RELATION_TYPE_ALREADY_EXIST,
        ERR_SAVE_DATA_FAILED,
        ERR_SEARCH_ENTRY_FAILED,
        ERR_SPOUSE_HAS_SAME_GENDER,
        ERR_UPDATE_ENTRY_FAILED,
        ERR_UPDATE_PERSON_FAILED,
        ERR_UPDATE_FAMILY_FAILED,
        ERR_UPDATE_RELATION_TYPE_FAILED,        
        

        MSG_ACTION_ON_DIED_PERSON,
        MSG_ADD_RELATIVE_ON_DIED_PERSON,
        MSG_CONFIRM_DEL_ENTRY,
        MSG_CONFIRM_DEL_FAMILY,
        MSG_CONFIRM_DEL_PERSON,
        MSG_ENTER_DATA,
        MSG_ENTER_FAMILY_NAME,
        MSG_ENTER_FIRSTNAME,
        MSG_ENTER_LASTNAME,
        MSG_FINISH_RELATIONSHIP,
        MSG_INVALID_AGE_CHILD_PARENT,
        MSG_MORE_THAN_ONE_HUSBAND,
        MSG_MORE_THAN_ONE_WIFE,
        MSG_NO_SPOUSE_BUT_HAS_CHILD,
        MSG_SELECT_GENDER,
        MSG_SELECT_RELATION_TYPE,
        MSG_SELECT_RELATIVE_PERSON,        
    }
}