//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTree.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTree.Common.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete family.
        /// </summary>
        internal static string ERR_DELETE_FAMILY_FAILED {
            get {
                return ResourceManager.GetString("ERR_DELETE_FAMILY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete person.
        /// </summary>
        internal static string ERR_DELETE_PERSON_FAILED {
            get {
                return ResourceManager.GetString("ERR_DELETE_PERSON_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of family {0} already exist.
        /// </summary>
        internal static string ERR_FAMILY_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("ERR_FAMILY_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new family.
        /// </summary>
        internal static string ERR_INSERT_FAMILY_FAILED {
            get {
                return ResourceManager.GetString("ERR_INSERT_FAMILY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new person.
        /// </summary>
        internal static string ERR_INSERT_PERSON_FAILED {
            get {
                return ResourceManager.GetString("ERR_INSERT_PERSON_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birthday.
        /// </summary>
        internal static string ERR_INVALID_BIRTHDAY {
            get {
                return ResourceManager.GetString("ERR_INVALID_BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        internal static string ERR_INVALID_DATE {
            get {
                return ResourceManager.GetString("ERR_INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load families&apos; information.
        /// </summary>
        internal static string ERR_LOAD_FAMILIES_FAILED {
            get {
                return ResourceManager.GetString("ERR_LOAD_FAMILIES_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update family information.
        /// </summary>
        internal static string ERR_UPDATE_FAMILY_FAILED {
            get {
                return ResourceManager.GetString("ERR_UPDATE_FAMILY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update person information.
        /// </summary>
        internal static string ERR_UPDATE_PERSON_FAILED {
            get {
                return ResourceManager.GetString("ERR_UPDATE_PERSON_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete the family of {0} ?
        ///CAUTION: This will delete all information of family members in database..
        /// </summary>
        internal static string MSG_CONFIRM_DEL_FAMILY {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DEL_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of family.
        /// </summary>
        internal static string MSG_ENTER_FAMILY_NAME {
            get {
                return ResourceManager.GetString("MSG_ENTER_FAMILY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the firstname.
        /// </summary>
        internal static string MSG_ENTER_FIRSTNAME {
            get {
                return ResourceManager.GetString("MSG_ENTER_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the lastname.
        /// </summary>
        internal static string MSG_ENTER_LASTNAME {
            get {
                return ResourceManager.GetString("MSG_ENTER_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the relative person and the relationship type. 
        ///You can leave both of them blank.
        /// </summary>
        internal static string MSG_FINISH_RELATIONSHIP {
            get {
                return ResourceManager.GetString("MSG_FINISH_RELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a gender.
        /// </summary>
        internal static string MSG_SELECT_GENDER {
            get {
                return ResourceManager.GetString("MSG_SELECT_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the type of thier relationship.
        /// </summary>
        internal static string MSG_SELECT_RELATION_TYPE {
            get {
                return ResourceManager.GetString("MSG_SELECT_RELATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select relative of this person.
        /// </summary>
        internal static string MSG_SELECT_RELATIVE_PERSON {
            get {
                return ResourceManager.GetString("MSG_SELECT_RELATIVE_PERSON", resourceCulture);
            }
        }
    }
}
